spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gosu_catcher # (본인 DB URL)
    username: sa
    password:
    driver-class-name: org.h2.Driver #(본인 DB종류에 맞춰서)
  h2:
    console:
      enabled: true
  jwt:
    accessTokenSecretKey: DEV_COURSE_TEAM_F_PROJECT_GOSU_CATCHER_DUMMY_ACCESS_TOKEN_SECRET
    refreshTokenSecretKey: DEV_COURSE_TEAM_F_PROJECT_GOSU_CATCHER_DUMMY_REFRESH_TOKEN_SECRET
    accessTokenExpiredTime: 3600000  # 예: 1시간 (밀리초)
    refreshTokenExpiredTime: 2592000000  # 예: 30일 (밀리초)

  jpa: # depth 주의
      open-in-view: true
      hibernate:
        ddl-auto: create              
        
      properties:
        hibernate:
          format_sql: true
      defer-datasource-initialization: true # 필수
  sql: # depth 주의 jpa와 같은 depth
      init:
        data-locations: classpath:data.sql
        mode: always
        platform: h2 # 본인 DB 종류
  config:
    import:
      - classpath:/application-aws.yml
      - classpath:/application-db.yml
      - classpath:/application-mail.yml
      
logging:
  level:
    org.hibernate.SQL: DEBUG  # 실행되는 SQL 쿼리를 출력
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE             
      
secret:
  coolsms:
    apiKey: DUMMY_KEY
    apiSecret: DUMMY_SECRET
    fromNumber: DUMMY_PHONE_NUMBER
    domain: https://api.coolsms.co.kr
    expirationTime: 600